"""empty message

Revision ID: 52b3cdee5568
Revises: 62c2747a5145
Create Date: 2019-07-20 22:51:07.162561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b3cdee5568'
down_revision = '62c2747a5145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoices_products_qty_fkey', 'invoices_products', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('invoices_products_qty_fkey', 'invoices_products', 'products', ['qty'], ['id'])
    # ### end Alembic commands ###
